name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-tests:
    uses: "./.github/workflows/build.yml"

  security:
    needs: build-and-tests
    permissions:
      security-events: write
    uses: "./.github/workflows/security.yml"

  docker:
    needs: security
    uses: "./.github/workflows/docker.yml"

  report:
    needs: docker
    uses: "./.github/workflows/report.yml"
